USE FDB;

-- Drop tables
DROP TABLE IF EXISTS Kadencja_Prezesa;
DROP TABLE IF EXISTS Prezes;
DROP TABLE IF EXISTS Kontrakt_Trenera;
DROP TABLE IF EXISTS Trener;
DROP TABLE IF EXISTS Stanowisko;
DROP TABLE IF EXISTS Kontrakt_Zawodnika;
DROP TABLE IF EXISTS Statystyki_Zawodnika;
DROP TABLE IF EXISTS Zawodnik;
DROP TABLE IF EXISTS Pozycja;
DROP TABLE IF EXISTS Mecz;
DROP TABLE IF EXISTS Uczestnictwo_w_Sezonie;
DROP TABLE IF EXISTS Klub_Sportowy;
DROP TABLE IF EXISTS Miasto;
DROP TABLE IF EXISTS Nazwa_Klubu;
DROP TABLE IF EXISTS Sezon;
DROP TABLE IF EXISTS Czlonek_Klubu;

-- Drop functions
DROP FUNCTION IF EXISTS IS_CHAR;
DROP FUNCTION IF EXISTS IS_RESULT;
DROP FUNCTION IF EXISTS CHECK_DATA;

DROP VIEW IF EXISTS SrednieWynagrodzenia;
DROP VIEW IF EXISTS PilkarzSrednia;
DROP VIEW IF EXISTS NajlepszyPilkarz;
DROP VIEW IF EXISTS KoniecKontraktu;
DROP VIEW IF EXISTS Top10Wynagrodzen;
DROP VIEW IF EXISTS StatystykiPilkarza;
DROP VIEW IF EXISTS WidokSezonu;
